platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
target 'rnPhoneAuthDemo' do
  # Pods for rnPhoneAuthDemo
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])


  target 'rnPhoneAuthDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'rnPhoneAuthDemo-tvOS' do
  # Pods for rnPhoneAuthDemo-tvOS

  target 'rnPhoneAuthDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
